name: compound_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy=0.17.0
  - cmocean=2.0
  - dask=2.10.1
  - geopandas=0.6.3
  - joblib=0.14.1
  - jupyter=1.0.0
  - matplotlib=3.1.3
  - netcdf4=1.5.3
  - numba=0.48.0
  - numpy=1.18.1
  - pandas=1.0.1
  - pip=20.0.2
  - python=3.7.6
  - rasterio=1.1.2
  - rtree=0.9.3
  - scipy=1.4.1
  - seaborn=0.10.0
  - shapely=1.7.0
  - statsmodels=0.11.0
  - xarray=0.15.0
  - zarr=2.4.0
  - pip:
    - numdifftools==0.9.39
    - git+https://gitlab.com/deltares/wflow/pyflwdir.git@hydromt
    - git+https://github.com/OpenHydrology/lmoments3.git